### PR TITLE
Update megacity records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes a portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/1547

- Updates megacity records with new:
  - concordances
  - names (if not already present)
  - label centroids
  - megacity flags
- Updates geometries of any megacity record with a `Point` geometry
- Updates parent geometries when necessary

### CODE REVIEW

**Review by nvkelso — APPROVED** [review]
LGTM

I'm fine to keep those unknown srcs, but it has to be either Quattroshapes point gazetteer or GeoNames.

**Comment by nvkelso** [comment]
And similar comment as to the Pakistan PR... can you do a pass to make sure any other localities that fall in the new megacity locality polygons are demoted to placetype `neighbourhood`, please?

**Comment by stepps00** [comment]
> And similar comment as to the Pakistan PR... can you do a pass to make sure any other localities that fall in the new megacity locality polygons are demoted to placetype neighbourhood, please?

I will likely merge these PRs as-is to close the initial issue, then file a follow-up issue to tackle these overlapping locality points.

Also, we've previously reworked these overlapping locality points two ways; either moving them to a new record at the `neighbourhood` placetype, or flagging them with a `"mz:is_funky":1` flag. I'm not sure which approach is best for these megacities, but I'll have a better idea once this initial work is merged.

**Comment by stepps00** [comment]
> I'm fine to keep those unknown srcs, but it has to be either Quattroshapes point gazetteer or GeoNames.

Just noting that this "unknown" issue is being tracked here: https://github.com/whosonfirst-data/whosonfirst-data/issues/1275

**Comment by nvkelso** [comment]
Filed followup in https://github.com/whosonfirst-data/whosonfirst-data/issues/1917.

**Pull request merged**
